import { useForm, useFieldArray } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { X, Upload, Plus } from 'lucide-react';
import type { Product, ProductFormData } from '../../types';
import { cn } from '../../lib/utils';
import { useState, useEffect } from 'react';
import { useMolds } from '../../hooks/useMolds';

// Options for dropdowns
const PRODUCT_TYPES = [
    { value: 'percinli', label: 'Perçinli' },
    { value: 'sivama', label: 'Sıvama' },
] as const;

const PERCINLI_SHAPES = [
    'Kare', 'Oval', 'Sekizgen', 'Dikdörtgen', 'Yuvarlak', 'Kalpli', 'Tepsi', 'Konik', 'Özel'
] as const;

// Helper to sort dimensions naturally (e.g. 55x55, 100x100)
const sortDimensions = (a: { dimensions: string }, b: { dimensions: string }) => {
    const getFirstNum = (s: string) => parseInt(s.split('x')[0]) || 0;
    return getFirstNum(a.dimensions) - getFirstNum(b.dimensions);
};


const productSchema = z.object({
    code: z.string().optional(), // Generated by backend
    name: z.string().min(2, 'Ürün adı en az 2 karakter olmalıdır'),
    productType: z.enum(['percinli', 'sivama']),
    boxShape: z.string().min(1, 'Kutu şekli seçimi zorunludur'),
    
    // Dimensions are now mandatory
    dimensions: z.object({
        length: z.coerce.number().min(0.1, 'Boy bilgisi zorunludur'),
        width: z.coerce.number().min(0.1, 'En bilgisi zorunludur'),
        depth: z.coerce.number().min(0, 'Yükseklik bilgisi zorunludur'),
    }),

    // OPTIONAL FIELDS - VALIDATION DISABLED
    inks: z.any().optional(),
    features: z.any().optional(),
    details: z.any().optional(),
    windowDetails: z.any().optional(),
    lidDetails: z.any().optional(),
    images: z.any().optional(),
});

interface ProductFormProps {
    initialData?: Product;
    onSubmit: (data: ProductFormData) => void;
    onCancel: () => void;
}

const defaultInks = {
    cmyk: false, white: false, pantones: [], 
    goldLak: { has: false }, emaye: { has: false }, astar: { has: false }, silverLak: { has: false },
    printType: { selected: false }
};

const defaultFeatures = {
    window: { selected: false },
    lid: { selected: false },
    gofre: { selected: false },
    bottom: { selected: false },
    accessory: { selected: false },
    packaging: { selected: false },
    extras: ''
};

export function ProductForm({ initialData, onSubmit, onCancel }: ProductFormProps) {
    const { molds } = useMolds();
    const { register, handleSubmit, watch, setValue, getValues, reset, formState: { errors } } = useForm<ProductFormData>({
        resolver: zodResolver(productSchema) as any,
        defaultValues: initialData ? {
            ...initialData,
            name: initialData.name || initialData.description || '',
            productType: initialData.productType || 'percinli',
            inks: initialData.inks || defaultInks,
            features: initialData.features || defaultFeatures
        } : {
            code: 'Otomatik',
            name: '',
            productType: 'percinli',
            dimensions: { length: 0, width: 0, depth: 0 },
            inks: defaultInks,
            features: defaultFeatures,
            details: '',
            windowDetails: { width: 0, height: 0, count: 1 },
            lidDetails: { 
                material: '', paint: '', notes: '', hasGofre: false, hasWindow: false, 
                windowDimensions: { width: 0, height: 0 },
                dimensions: { length: 0, width: 0, depth: 0 }
            },
            images: { customer: [] },
        },
    });

    // Reset form when initialData changes (e.g. selecting a different product in Design page)
    useEffect(() => {
        if (initialData) {
            reset({
                ...initialData,
                name: initialData.name || initialData.description || '',
                productType: initialData.productType || 'percinli',
                inks: initialData.inks || defaultInks,
                features: initialData.features || defaultFeatures
            });
        }
    }, [initialData, reset]);

    const productType = watch('productType');
    const boxShape = watch('boxShape');
    const customerImages = watch('images.customer') || [];
    const pantones = watch('inks.pantones') || [];
    const [newPantone, setNewPantone] = useState('');

    // Watchers for new Features
    const winSelected = watch('features.window.selected');
    const winType = watch('features.window.value');
    const lidSelected = watch('features.lid.selected');
    const gofreSelected = watch('features.gofre.selected');
    const bottomSelected = watch('features.bottom.selected');
    const bottomType = watch('features.bottom.value');
    const accSelected = watch('features.accessory.selected');
    const pkgSelected = watch('features.packaging.selected');

    // Watchers for Print Type
    const printTypeType = watch('inks.printType.value');

    // Dimension helpers for Percinli Square
    const dimLength = watch('dimensions.length');
    const dimWidth = watch('dimensions.width');
    const dimDepth = watch('dimensions.depth');
    const currentBaseDim = (dimLength && dimWidth) ? `${dimLength}x${dimWidth}` : '';

    const handleBaseDimChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
        const val = e.target.value;
        if (!val) {
            setValue('dimensions.length', undefined);
            setValue('dimensions.width', undefined);
            return;
        }
        const [l, w] = val.split('x').map(Number);
        setValue('dimensions.length', l);
        setValue('dimensions.width', w);
    };

    const handleHeartDimChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
        const val = e.target.value;
        if (!val) {
            setValue('dimensions.length', undefined);
            setValue('dimensions.width', undefined);
            setValue('dimensions.depth', undefined);
            return;
        }
        const parts = val.split('x').map(Number);
        if (parts.length === 3) {
            setValue('dimensions.length', parts[0]);
            setValue('dimensions.width', parts[1]);
            setValue('dimensions.depth', parts[2]);
        } else {
            setValue('dimensions.length', parts[0]);
            setValue('dimensions.width', parts[1]);
            setValue('dimensions.depth', undefined);
        }
    };

    const handleConicDimChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
        const val = e.target.value;
        if (!val) {
            setValue('dimensions.length', undefined);
            setValue('dimensions.width', undefined);
            setValue('dimensions.depth', undefined);
            return;
        }
        const parts = val.split('x').map(Number);
        if (parts.length === 3) {
            setValue('dimensions.length', parts[0]);
            setValue('dimensions.width', parts[1]);
            setValue('dimensions.depth', parts[2]);
        }
    };

    // Watch Inks for conditional inputs
    const hasGoldLak = watch('inks.goldLak.has');
    const hasEmaye = watch('inks.emaye.has');
    const hasAstar = watch('inks.astar.has');
    const hasSilverLak = watch('inks.silverLak.has');

    // Reset boxShape if not valid for the selected productType
    useEffect(() => {
        const currentShape = getValues('boxShape');
        if (!currentShape) return;

        if (productType === 'percinli') {
            if (!PERCINLI_SHAPES.includes(currentShape as any)) {
                setValue('boxShape', undefined);
            }
        } else if (productType === 'sivama') {
            // Check against dynamic molds if loaded
            if (molds.length > 0) {
                const validShapes = molds
                    .filter(m => m.productType === 'sivama')
                    .map(m => m.dimensions);
                if (!validShapes.includes(currentShape)) {
                    setValue('boxShape', undefined);
                }
            }
        }
    }, [productType, setValue, getValues, molds]);

    // Auto-fill dimensions for Sivama based on boxShape selection
    useEffect(() => {
        if (productType === 'sivama' && boxShape) {
            // boxShape is like "100x200x50" or "100x200"
            const parts = boxShape.split('x').map(p => parseFloat(p));
            if (!parts.some(isNaN) && parts.length > 0) {
                if (parts.length === 3) {
                     // WxLxH
                     setValue('dimensions.length', parts[0]);
                     setValue('dimensions.width', parts[1]);
                     setValue('dimensions.depth', parts[2]);
                } else if (parts.length === 2) {
                     // Assume DiaxH or WxL? Let's assume WxL and Depth=0 (user might need to edit?)
                     // But Sivama doesn't show dimension inputs. 
                     // So we must ensure it passes validation or we are stuck.
                     // Mapping 2 parts to Length/Width and Depth=0
                     setValue('dimensions.length', parts[0]);
                     setValue('dimensions.width', parts[1]);
                     setValue('dimensions.depth', 0);
                } else if (parts.length === 1) {
                     // Assume Diameter?
                     setValue('dimensions.length', parts[0]);
                     setValue('dimensions.width', parts[0]);
                     setValue('dimensions.depth', 0);
                }
            }
        }
    }, [productType, boxShape, setValue]);

    const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
        const files = e.target.files;
        if (!files) return;

        if (customerImages.length + files.length > 2) {
            alert('En fazla 2 resim yükleyebilirsiniz.');
            return;
        }

        const uploadedUrls: string[] = [];

        for (let i = 0; i < files.length; i++) {
            const file = files[i];
            const formData = new FormData();
            formData.append('image', file);

            try {
                const response = await fetch('/api/upload', {
                    method: 'POST',
                    body: formData,
                });
                
                if (response.ok) {
                    const data = await response.json();
                    uploadedUrls.push(data.url);
                } else {
                    console.error('Upload failed');
                    alert('Resim yüklenirken bir hata oluştu.');
                }
            } catch (error) {
                console.error('Error uploading image:', error);
                alert('Resim yüklenirken bir hata oluştu.');
            }
        }
        
        if (uploadedUrls.length > 0) {
             const newImages = [...customerImages, ...uploadedUrls];
             setValue(`images.customer`, newImages);
        }
    };

    const removeImage = (index: number) => {
        const newImages = customerImages.filter((_, i) => i !== index);
        setValue(`images.customer`, newImages);
    };

    const addPantone = () => {
        if (newPantone.trim()) {
            if (pantones.length >= 10) {
                alert('En fazla 10 Pantone kodu girebilirsiniz.');
                return;
            }
            setValue('inks.pantones', [...pantones, newPantone.trim()]);
            setNewPantone('');
        }
    };

    const removePantone = (index: number) => {
        setValue('inks.pantones', pantones.filter((_, i) => i !== index));
    };

    return (
        <form 
            onSubmit={handleSubmit(onSubmit as any, (errors) => {
                console.error('Form Validation Errors:', errors);
                // Alert user about validation errors
                const errorMessages = Object.values(errors)
                    .map((err: any) => err.message)
                    .filter(Boolean)
                    .join('\n');
                
                if (errorMessages) {
                    alert(`Lütfen aşağıdaki hataları düzeltin:\n${errorMessages}`);
                } else {
                    alert('Lütfen zorunlu alanları doldurunuz.');
                }
            })} 
            className="space-y-6"
        >
            {/* TEMEL BILGILER */}
            <div className="space-y-4">
                <h4 className="text-sm font-semibold text-slate-800 border-b pb-2">Temel Bilgiler</h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-1">
                        <label className="text-sm font-medium text-slate-700">Ürün Kodu</label>
                        <input
                            disabled
                            value={initialData?.code || "Otomatik Oluşturulacak (GMP...)"}
                            className="w-full px-3 py-2 border border-slate-200 bg-slate-50 rounded-lg text-slate-500 cursor-not-allowed"
                            aria-label="Ürün Kodu"
                        />
                    </div>
                    <div className="space-y-1">
                        <label className="text-sm font-medium text-slate-700">Ürün Adı</label>
                        <input
                            {...register('name')}
                            className={cn(
                                "w-full px-3 py-2 border rounded-lg outline-none focus:ring-2 focus:ring-indigo-500 transition-all",
                                errors.name ? "border-red-500" : "border-slate-300"
                            )}
                            placeholder="Örn: Yuvarlak Kutu"
                            aria-label="Ürün Adı"
                        />
                        {errors.name && <p className="text-xs text-red-500">{errors.name.message}</p>}
                    </div>
                </div>
            </div>

            {/* ÜRÜN ŞEKLİ */}
            <div className="space-y-4">
                <h4 className="text-sm font-semibold text-slate-800 border-b pb-2">Ürün Şekli</h4>
                <div className="space-y-4">
                    <div className="space-y-2">
                        <label className="text-sm font-medium text-slate-700">Ürün Tipi</label>
                        <div className="flex gap-4">
                            {PRODUCT_TYPES.map(type => (
                                <label key={type.value} className="flex items-center gap-2 cursor-pointer">
                                    <input
                                        type="radio"
                                        value={type.value}
                                        {...register('productType')}
                                        className="w-4 h-4 text-indigo-600 border-gray-300 focus:ring-indigo-500"
                                        aria-label={type.label}
                                    />
                                    <span className="text-sm text-slate-700">{type.label}</span>
                                </label>
                            ))}
                        </div>
                    </div>

                    {(productType === 'percinli' || productType === 'sivama') && (
                        <div className="space-y-2 animate-in fade-in slide-in-from-top-2">
                            <label className="text-sm font-medium text-slate-700">Kutu Şekli / Ölçü</label>
                            <select
                                {...register('boxShape')}
                                className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                aria-label="Kutu Şekli"
                            >
                                <option value="">Seçiniz...</option>
                                {productType === 'percinli' && PERCINLI_SHAPES.map(shape => (
                                    <option key={shape} value={shape}>{shape}</option>
                                ))}
                                {productType === 'sivama' && molds
                                    .filter(m => m.productType === 'sivama')
                                    .map(m => (
                                    <option key={m.id} value={m.dimensions}>{m.dimensions}</option>
                                ))}
                            </select>
                        </div>
                    )}

                    {/* Perçinli + Kare -> Base Dimensions + Depth */}
                    {productType === 'percinli' && boxShape === 'Kare' && (
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Taban Ölçüsü (mm)</label>
                                <select
                                    value={currentBaseDim}
                                    onChange={handleBaseDimChange}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                    aria-label="Taban Ölçüsü"
                                >
                                    <option value="">Seçiniz...</option>
                                    {molds.filter(m => m.boxShape === 'Kare').sort(sortDimensions).map(m => (
                                        <option key={m.id} value={m.dimensions}>{m.dimensions}</option>
                                    ))}
                                </select>
                            </div>
                            {currentBaseDim && (
                                <div className="space-y-2 animate-in fade-in slide-in-from-left-2">
                                    <label className="text-sm font-medium text-slate-700">Boy / Yükseklik (mm)</label>
                                    <input
                                        type="number"
                                        placeholder="0"
                                        {...register('dimensions.depth')}
                                        className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                        aria-label="Yükseklik"
                                    />
                                </div>
                            )}
                        </div>
                    )}

                    {/* Perçinli + Oval -> Base Dimensions + Depth */}
                    {productType === 'percinli' && boxShape === 'Oval' && (
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Taban Ölçüsü (mm)</label>
                                <select
                                    value={currentBaseDim}
                                    onChange={handleBaseDimChange}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                    aria-label="Taban Ölçüsü"
                                >
                                    <option value="">Seçiniz...</option>
                                    {molds.filter(m => m.boxShape === 'Oval').sort(sortDimensions).map(m => (
                                        <option key={m.id} value={m.dimensions}>{m.dimensions}</option>
                                    ))}
                                </select>
                            </div>
                            {currentBaseDim && (
                                <div className="space-y-2 animate-in fade-in slide-in-from-left-2">
                                    <label className="text-sm font-medium text-slate-700">Boy / Yükseklik (mm)</label>
                                    <input
                                        type="number"
                                        placeholder="0"
                                        {...register('dimensions.depth')}
                                        className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                        aria-label="Yükseklik"
                                    />
                                </div>
                            )}
                        </div>
                    )}
                    
                    {/* Perçinli + Sekizgen -> Base Dimensions + Depth */}
                    {productType === 'percinli' && boxShape === 'Sekizgen' && (
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Taban Ölçüsü (mm)</label>
                                <select
                                    value={currentBaseDim}
                                    onChange={handleBaseDimChange}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                    aria-label="Taban Ölçüsü"
                                >
                                    <option value="">Seçiniz...</option>
                                    {molds.filter(m => m.boxShape === 'Sekizgen').sort(sortDimensions).map(m => (
                                        <option key={m.id} value={m.dimensions}>{m.dimensions}</option>
                                    ))}
                                </select>
                            </div>
                            {currentBaseDim && (
                                <div className="space-y-2 animate-in fade-in slide-in-from-left-2">
                                    <label className="text-sm font-medium text-slate-700">Boy / Yükseklik (mm)</label>
                                    <input
                                        type="number"
                                        placeholder="0"
                                        {...register('dimensions.depth')}
                                        className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                    />
                                </div>
                            )}
                        </div>
                    )}

                    {/* Perçinli + Dikdörtgen -> Base Dimensions + Depth */}
                    {productType === 'percinli' && boxShape === 'Dikdörtgen' && (
                        <div className="grid grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Taban Ölçüsü (mm)</label>
                                <select
                                    value={currentBaseDim}
                                    onChange={handleBaseDimChange}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                >
                                    <option value="">Seçiniz...</option>
                                    {molds.filter(m => m.boxShape === 'Dikdörtgen').sort(sortDimensions).map(m => (
                                        <option key={m.id} value={m.dimensions}>{m.dimensions}</option>
                                    ))}
                                </select>
                            </div>
                            {currentBaseDim && (
                                <div className="space-y-2 animate-in fade-in slide-in-from-left-2">
                                    <label className="text-sm font-medium text-slate-700">Boy / Yükseklik (mm)</label>
                                    <input
                                        type="number"
                                        placeholder="0"
                                        {...register('dimensions.depth')}
                                        className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                    />
                                </div>
                            )}
                        </div>
                    )}

                    {/* Perçinli + Yuvarlak -> Diameter + Depth */}
                    {productType === 'percinli' && boxShape === 'Yuvarlak' && (
                        <div className="grid grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Çap (Ø)</label>
                                <select
                                    value={currentBaseDim}
                                    onChange={handleBaseDimChange}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                >
                                    <option value="">Seçiniz...</option>
                                    {molds.filter(m => m.boxShape === 'Yuvarlak').sort(sortDimensions).map(m => (
                                        <option key={m.id} value={`${m.dimensions}x${m.dimensions}`}>{m.label || `Ø${m.dimensions}`}</option>
                                    ))}
                                </select>
                            </div>
                            {currentBaseDim && (
                                <div className="space-y-2 animate-in fade-in slide-in-from-left-2">
                                    <label className="text-sm font-medium text-slate-700">Boy / Yükseklik (mm)</label>
                                    <input
                                        type="number"
                                        placeholder="0"
                                        {...register('dimensions.depth')}
                                        className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                    />
                                </div>
                            )}
                        </div>
                    )}

                    {/* Perçinli + Kalpli -> Specific Logic */}
                    {productType === 'percinli' && boxShape === 'Kalpli' && (
                        <div className="grid grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Taban Ölçüsü (mm)</label>
                                <select
                                    value={(dimLength && dimWidth) ? (
                                        molds.filter(m => m.boxShape === 'Kalpli').find(m => 
                                            m.dimensions === `${dimLength}x${dimWidth}x${dimDepth}`
                                        )?.dimensions || `${dimLength}x${dimWidth}`
                                    ) : ''}
                                    onChange={handleHeartDimChange}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                >
                                    <option value="">Seçiniz...</option>
                                    {molds.filter(m => m.boxShape === 'Kalpli').sort(sortDimensions).map(m => (
                                        <option key={m.id} value={m.dimensions}>{m.label || m.dimensions}</option>
                                    ))}
                                </select>
                            </div>
                            
                            {/* Show depth input unless we have matched a 3-part mold dimensions exactly */}
                            {dimLength && dimWidth && !molds.some(m => m.boxShape === 'Kalpli' && m.dimensions === `${dimLength}x${dimWidth}x${dimDepth}`) && (
                                <div className="space-y-2 animate-in fade-in slide-in-from-left-2">
                                    <label className="text-sm font-medium text-slate-700">Boy / Yükseklik (mm)</label>
                                    <input
                                        type="number"
                                        placeholder="0"
                                        {...register('dimensions.depth')}
                                        className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                    />
                                </div>
                            )}
                        </div>
                    )}

                    {/* Perçinli + Tepsi -> Base Dimensions + Special Label Depth */}
                    {productType === 'percinli' && boxShape === 'Tepsi' && (
                        <div className="grid grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Taban Ölçüsü (mm)</label>
                                <select
                                    value={currentBaseDim}
                                    onChange={handleBaseDimChange}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                >
                                    <option value="">Seçiniz...</option>
                                    {molds.filter(m => m.boxShape === 'Tepsi').sort(sortDimensions).map(m => (
                                        <option key={m.id} value={m.dimensions}>{m.label || m.dimensions}</option>
                                    ))}
                                </select>
                            </div>
                            {currentBaseDim && (
                                <div className="space-y-2 animate-in fade-in slide-in-from-left-2">
                                    <label className="text-sm font-medium text-slate-700">Ek ölçü varsa belirtin</label>
                                    <input
                                        type="number"
                                        placeholder="0"
                                        {...register('dimensions.depth')}
                                        className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                    />
                                </div>
                            )}
                        </div>
                    )}

                    {/* Perçinli + Konik -> Fixed Dimensions (No extra depth input) */}
                    {productType === 'percinli' && boxShape === 'Konik' && (
                        <div className="grid grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Ölçü (mm)</label>
                                <select
                                    value={(dimLength && dimWidth && dimDepth) ? `${dimLength}x${dimWidth}x${dimDepth}` : ''}
                                    onChange={handleConicDimChange}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                >
                                    <option value="">Seçiniz...</option>
                                    {molds.filter(m => m.boxShape === 'Konik').sort(sortDimensions).map(m => (
                                        <option key={m.id} value={m.dimensions}>{m.label || m.dimensions}</option>
                                    ))}
                                </select>
                            </div>
                        </div>
                    )}

                    {/* Perçinli + Özel -> Manual Dimensions */}
                    {productType === 'percinli' && boxShape === 'Özel' && (
                        <div className="grid grid-cols-3 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">En (mm)</label>
                                <input
                                    type="number"
                                    placeholder="0"
                                    {...register('dimensions.width')}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                />
                            </div>
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Genişlik (mm)</label>
                                <input
                                    type="number"
                                    placeholder="0"
                                    {...register('dimensions.length')}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                />
                            </div>
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Boy (mm)</label>
                                <input
                                    type="number"
                                    placeholder="0"
                                    {...register('dimensions.depth')}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                />
                            </div>
                        </div>
                    )}

                    {/* Placeholder for Dimensions */}
                    {!(productType === 'percinli' && (boxShape === 'Kare' || boxShape === 'Oval' || boxShape === 'Sekizgen' || boxShape === 'Dikdörtgen' || boxShape === 'Yuvarlak' || boxShape === 'Kalpli' || boxShape === 'Tepsi' || boxShape === 'Konik' || boxShape === 'Özel')) && (
                        <div className="p-3 bg-yellow-50 border border-yellow-200 rounded text-sm text-yellow-800">
                            Ölçüler kategorilere göre daha sonra detaylandırılacaktır.
                        </div>
                    )}
                </div>
            </div>

            {/* MÜREKKEPLER */}
            <div className="space-y-4">
                <h4 className="text-sm font-semibold text-slate-800 border-b pb-2">Mürekkepler</h4>
                
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    <label className="flex items-center gap-2 p-3 border rounded-lg cursor-pointer hover:bg-slate-50">
                        <input type="checkbox" {...register('inks.cmyk')} className="w-4 h-4 text-indigo-600 rounded" />
                        <span className="text-sm font-medium">CMYK</span>
                    </label>
                    <label className="flex items-center gap-2 p-3 border rounded-lg cursor-pointer hover:bg-slate-50">
                        <input type="checkbox" {...register('inks.white')} className="w-4 h-4 text-indigo-600 rounded" />
                        <span className="text-sm font-medium">Beyaz</span>
                    </label>
                </div>

                <div className="space-y-2">
                    <label className="text-sm font-medium text-slate-700">Baskı Şekli</label>
                    <div className="flex gap-4 items-center">
                         {['dijital', 'ofset', 'dijital_ofset'].map((type) => (
                            <label key={type} className="flex items-center gap-2 cursor-pointer">
                                <input 
                                    type="radio" 
                                    value={type}
                                    {...register('inks.printType.value')}
                                    className="w-4 h-4 text-indigo-600"
                                />
                                <span className="text-sm text-slate-700">
                                    {type === 'dijital_ofset' ? 'Dijital + Ofset' : type.charAt(0).toUpperCase() + type.slice(1)}
                                </span>
                            </label>
                         ))}
                    </div>
                    {/* Note input for Dijital + Ofset */}
                    {printTypeType === 'dijital_ofset' && (
                        <div className="mt-2">
                             <input 
                                {...register('inks.printType.note')}
                                placeholder="Not giriniz..."
                                className="w-full px-3 py-2 border rounded-lg text-sm outline-none focus:ring-2 focus:ring-indigo-500"
                            />
                        </div>
                    )}
                </div>

                <div className="space-y-2">
                    <label className="text-sm font-medium text-slate-700">Pantone Kodları</label>
                    <div className="flex gap-2">
                        <input 
                            value={newPantone}
                            onChange={(e) => setNewPantone(e.target.value)}
                            placeholder="Kod (Örn: C0000)"
                            className="flex-1 px-3 py-1.5 border rounded text-sm outline-none focus:border-indigo-500"
                            aria-label="Pantone Kodu"
                            onKeyDown={(e) => {
                                if (e.key === 'Enter') {
                                    e.preventDefault();
                                    addPantone();
                                }
                            }}
                        />
                        <button
                            type="button"
                            onClick={addPantone}
                            className="text-xs flex items-center gap-1 bg-indigo-50 text-indigo-600 px-3 py-1.5 rounded hover:bg-indigo-100 whitespace-nowrap"
                        >
                            <Plus size={14} /> Ekle
                        </button>
                    </div>
                    
                    {pantones.length > 0 ? (
                        <div className="flex flex-wrap gap-2 mt-2">
                            {pantones.map((code, index) => (
                                <div key={index} className="flex items-center gap-1 bg-slate-100 px-2 py-1 rounded text-sm border border-slate-200">
                                    <span>{code}</span>
                                    <button type="button" onClick={() => removePantone(index)} className="text-slate-400 hover:text-red-500" aria-label="Pantone Sil">
                                        <X size={14} />
                                    </button>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <p className="text-xs text-slate-400 italic mt-1">Henüz pantone kodu eklenmedi.</p>
                    )}
                </div>

                <div className="space-y-3 pt-2">
                    {/* Gold Lak */}
                    <div className="flex items-center gap-4">
                        <label className="flex items-center gap-2 w-32">
                            <input type="checkbox" {...register('inks.goldLak.has')} className="w-4 h-4 text-indigo-600 rounded" />
                            <span className="text-sm">Gold Lak</span>
                        </label>
                        {hasGoldLak && (
                            <input 
                                {...register('inks.goldLak.code')} 
                                placeholder="Kod giriniz" 
                                className="flex-1 px-3 py-1.5 border rounded text-sm outline-none focus:border-indigo-500"
                            />
                        )}
                    </div>
                    {/* Emaye */}
                    <div className="flex items-center gap-4">
                        <label className="flex items-center gap-2 w-32">
                            <input type="checkbox" {...register('inks.emaye.has')} className="w-4 h-4 text-indigo-600 rounded" />
                            <span className="text-sm">Emaye</span>
                        </label>
                        {hasEmaye && (
                            <input 
                                {...register('inks.emaye.code')} 
                                placeholder="Kod giriniz" 
                                className="flex-1 px-3 py-1.5 border rounded text-sm outline-none focus:border-indigo-500"
                            />
                        )}
                    </div>
                    {/* Astar */}
                    <div className="flex items-center gap-4">
                        <label className="flex items-center gap-2 w-32">
                            <input type="checkbox" {...register('inks.astar.has')} className="w-4 h-4 text-indigo-600 rounded" />
                            <span className="text-sm">Astar</span>
                        </label>
                        {hasAstar && (
                            <input 
                                {...register('inks.astar.code')} 
                                placeholder="Kod giriniz" 
                                className="flex-1 px-3 py-1.5 border rounded text-sm outline-none focus:border-indigo-500"
                            />
                        )}
                    </div>
                    {/* Silver Lak */}
                    <div className="flex items-center gap-4">
                        <label className="flex items-center gap-2 w-32">
                            <input type="checkbox" {...register('inks.silverLak.has')} className="w-4 h-4 text-indigo-600 rounded" />
                            <span className="text-sm">Silver Lak</span>
                        </label>
                        {hasSilverLak && (
                            <input 
                                {...register('inks.silverLak.code')} 
                                placeholder="Kod giriniz" 
                                className="flex-1 px-3 py-1.5 border rounded text-sm outline-none focus:border-indigo-500"
                            />
                        )}
                    </div>
                </div>
            </div>

            {/* ÖZELLİKLER & DETAYLAR */}
            <div className="space-y-6">
                <h4 className="text-sm font-semibold text-slate-800 border-b pb-2">Özellikler & Detaylar</h4>
                
                {/* Pencere */}
                <div className="space-y-2 p-3 border rounded-lg bg-slate-50">
                    <label className="flex items-center gap-2 font-medium text-slate-800 cursor-pointer">
                        <input type="checkbox" {...register('features.window.selected')} className="w-4 h-4 text-indigo-600 rounded" />
                        Pencere
                    </label>
                    {winSelected && (
                        <div className="pl-6 space-y-2 animate-in fade-in slide-in-from-top-2">
                             <div className="flex flex-col gap-2">
                                {['kapakta', 'govdede', 'kapakta_govdede'].map((type) => (
                                    <div key={type} className="flex items-center gap-3">
                                        <label className="flex items-center gap-2 cursor-pointer w-40">
                                            <input 
                                                type="radio" 
                                                value={type}
                                                {...register('features.window.value')}
                                                className="w-4 h-4 text-indigo-600"
                                            />
                                            <span className="text-sm text-slate-700">
                                                {type === 'kapakta_govdede' ? 'Kapakta ve Gövdede' : type.charAt(0).toUpperCase() + type.slice(1)}
                                            </span>
                                        </label>
                                        {/* Note for each option (or shared note visible when type is selected) */}
                                        {winType === type && (
                                            <input 
                                                {...register('features.window.note')}
                                                placeholder={`${type === 'kapakta' ? 'Kapak' : type === 'govdede' ? 'Gövde' : 'Kapak ve Gövde'} pencere notu...`}
                                                className="flex-1 px-2 py-1 text-sm border rounded outline-none focus:border-indigo-500"
                                            />
                                        )}
                                    </div>
                                ))}
                             </div>
                        </div>
                    )}
                </div>

                {/* Kapak */}
                <div className="space-y-2 p-3 border rounded-lg bg-slate-50">
                    <label className="flex items-center gap-2 font-medium text-slate-800 cursor-pointer">
                        <input type="checkbox" {...register('features.lid.selected')} className="w-4 h-4 text-indigo-600 rounded" />
                        Kapak
                    </label>
                    {lidSelected && (
                        <div className="pl-6 flex flex-wrap gap-4 animate-in fade-in slide-in-from-top-2">
                            {[
                                { val: 'kapaksiz', label: 'Kapaksız' },
                                { val: 'ustten_gecme', label: 'Üstten Geçme' },
                                { val: 'ice_kivrim_ustten_gecme', label: 'İçe Kıvrım Üstten Geçme' },
                                { val: 'ice_giren', label: 'İçe Giren Kapak' },
                                { val: 'kristal', label: 'Kristal Kapak' },
                                { val: 'menteseli', label: 'Menteşeli' },
                                { val: 'puntolu', label: 'Puntolu' }
                            ].map((opt) => (
                                <label key={opt.val} className="flex items-center gap-2 cursor-pointer">
                                    <input 
                                        type="radio" 
                                        value={opt.val}
                                        {...register('features.lid.value')}
                                        className="w-4 h-4 text-indigo-600"
                                    />
                                    <span className="text-sm text-slate-700">{opt.label}</span>
                                </label>
                            ))}
                        </div>
                    )}
                </div>

                {/* Gofre */}
                <div className="space-y-2 p-3 border rounded-lg bg-slate-50">
                    <label className="flex items-center gap-2 font-medium text-slate-800 cursor-pointer">
                        <input type="checkbox" {...register('features.gofre.selected')} className="w-4 h-4 text-indigo-600 rounded" />
                        Gofre
                    </label>
                    {gofreSelected && (
                        <div className="pl-6 flex flex-wrap gap-4 animate-in fade-in slide-in-from-top-2">
                             {[
                                { val: 'govde', label: 'Gövde' },
                                { val: 'kapak', label: 'Kapak' },
                                { val: 'govde_kapak', label: 'Gövde ve Kapak' }
                            ].map((opt) => (
                                <label key={opt.val} className="flex items-center gap-2 cursor-pointer">
                                    <input 
                                        type="radio" 
                                        value={opt.val}
                                        {...register('features.gofre.value')}
                                        className="w-4 h-4 text-indigo-600"
                                    />
                                    <span className="text-sm text-slate-700">{opt.label}</span>
                                </label>
                            ))}
                        </div>
                    )}
                </div>

                {/* Dip */}
                <div className="space-y-2 p-3 border rounded-lg bg-slate-50">
                    <label className="flex items-center gap-2 font-medium text-slate-800 cursor-pointer">
                        <input type="checkbox" {...register('features.bottom.selected')} className="w-4 h-4 text-indigo-600 rounded" />
                        Dip
                    </label>
                    {bottomSelected && (
                        <div className="pl-6 space-y-2 animate-in fade-in slide-in-from-top-2">
                             <div className="flex flex-col gap-2">
                                {['baskili', 'baskisiz'].map((type) => (
                                    <div key={type} className="flex items-center gap-3">
                                        <label className="flex items-center gap-2 cursor-pointer w-32">
                                            <input 
                                                type="radio" 
                                                value={type}
                                                {...register('features.bottom.value')}
                                                className="w-4 h-4 text-indigo-600"
                                            />
                                            <span className="text-sm text-slate-700">
                                                {type === 'baskili' ? 'Baskılı' : 'Baskısız'}
                                            </span>
                                        </label>
                                        {bottomType === type && (
                                            <input 
                                                {...register('features.bottom.note')}
                                                placeholder="Not..."
                                                className="flex-1 px-2 py-1 text-sm border rounded outline-none focus:border-indigo-500"
                                            />
                                        )}
                                    </div>
                                ))}
                             </div>
                        </div>
                    )}
                </div>

                {/* Aksesuar */}
                <div className="space-y-2 p-3 border rounded-lg bg-slate-50">
                    <label className="flex items-center gap-2 font-medium text-slate-800 cursor-pointer">
                        <input type="checkbox" {...register('features.accessory.selected')} className="w-4 h-4 text-indigo-600 rounded" />
                        Aksesuar
                    </label>
                    {accSelected && (
                        <div className="pl-6 flex flex-wrap gap-4 animate-in fade-in slide-in-from-top-2">
                             {[
                                { val: 'kulp', label: 'Kulp' },
                                { val: 'sunger', label: 'Sünger' },
                                { val: 'ip', label: 'İp' }
                            ].map((opt) => (
                                <label key={opt.val} className="flex items-center gap-2 cursor-pointer">
                                    <input 
                                        type="radio" 
                                        value={opt.val}
                                        {...register('features.accessory.value')}
                                        className="w-4 h-4 text-indigo-600"
                                    />
                                    <span className="text-sm text-slate-700">{opt.label}</span>
                                </label>
                            ))}
                        </div>
                    )}
                </div>

                {/* Ambalaj Şekli */}
                <div className="space-y-2 p-3 border rounded-lg bg-slate-50">
                    <label className="flex items-center gap-2 font-medium text-slate-800 cursor-pointer">
                        <input type="checkbox" {...register('features.packaging.selected')} className="w-4 h-4 text-indigo-600 rounded" />
                        Ambalaj Şekli
                    </label>
                    {pkgSelected && (
                        <div className="pl-6 animate-in fade-in slide-in-from-top-2">
                            <input 
                                {...register('features.packaging.note')}
                                placeholder="Ambalaj şeklini yazınız..."
                                className="w-full px-3 py-2 border rounded-lg text-sm outline-none focus:ring-2 focus:ring-indigo-500"
                            />
                        </div>
                    )}
                </div>

            </div>
            
            {/* ÜRÜN DETAYLARI */}
            <div className="space-y-4">
                <h4 className="text-sm font-semibold text-slate-800 border-b pb-2">Ürün Detayları</h4>
                <div className="space-y-1">
                    <textarea
                        {...register('details')}
                        className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500 min-h-[100px]"
                        placeholder="Ek özellikler ve detaylar..."
                    />
                </div>
            </div>

            {/* ÜRÜN GÖRSELLERİ */}
            <div className="space-y-4">
                <h4 className="text-sm font-semibold text-slate-800 border-b pb-2">Ürün Görselleri</h4>
                
                <div className="space-y-3">
                    <label className="block text-sm font-medium text-slate-700">Müşteri Görseli (Jpeg, Png, Pdf)</label>
                    <div className="flex gap-4">
                        {customerImages.map((url, index) => (
                            <div key={index} className="relative w-24 h-24 border rounded-lg overflow-hidden group">
                                <img src={url} alt={`Customer ${index + 1}`} className="w-full h-full object-cover" />
                                <button
                                    type="button"
                                    onClick={() => removeImage(index)}
                                    className="absolute top-1 right-1 bg-red-500 text-white p-1 rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
                                    aria-label="Resmi Sil"
                                >
                                    <X size={12} />
                                </button>
                            </div>
                        ))}
                        {customerImages.length < 2 && (
                            <label className="w-24 h-24 border-2 border-dashed border-slate-300 rounded-lg flex flex-col items-center justify-center cursor-pointer hover:border-indigo-500 hover:bg-indigo-50 transition-all">
                                <Upload className="w-6 h-6 text-slate-400 mb-1" />
                                <span className="text-[10px] text-slate-500">Yükle</span>
                                <input type="file" className="hidden" accept="image/jpeg,image/png,application/pdf" onChange={handleImageUpload} aria-label="Resim Yükle" />
                            </label>
                        )}
                    </div>
                </div>
            </div>

            <div className="flex justify-end gap-3 pt-4 border-t">
                <button
                    type="button"
                    onClick={onCancel}
                    className="px-4 py-2 text-sm font-medium text-slate-700 bg-white border border-slate-300 rounded-lg hover:bg-slate-50"
                    aria-label="İptal"
                >
                    İptal
                </button>
                <button
                    type="submit"
                    className="px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-lg hover:bg-indigo-700"
                    aria-label="Kaydet"
                >
                    Kaydet
                </button>
            </div>
        </form>
    );
}
