import { useForm, useFieldArray } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { X, Upload, Plus } from 'lucide-react';
import type { Product, ProductFormData } from '../../types';
import { cn } from '../../lib/utils';
import { useState, useEffect } from 'react';
import { useMolds } from '../../hooks/useMolds';

// Options for dropdowns
const PRODUCT_TYPES = [
    { value: 'percinli', label: 'Perçinli' },
    { value: 'sivama', label: 'Sıvama' },
] as const;

const PERCINLI_SHAPES = [
    'Kare', 'Oval', 'Sekizgen', 'Dikdörtgen', 'Yuvarlak', 'Kalpli', 'Tepsi', 'Konik', 'Özel'
] as const;

// Helper to sort dimensions naturally (e.g. 55x55, 100x100)
const sortDimensions = (a: { dimensions: string }, b: { dimensions: string }) => {
    const getFirstNum = (s: string) => parseInt(s.split('x')[0]) || 0;
    return getFirstNum(a.dimensions) - getFirstNum(b.dimensions);
};


const productSchema = z.object({
    code: z.string().optional(), // Generated by backend
    name: z.string().min(2, 'Ürün adı en az 2 karakter olmalıdır'),
    productType: z.enum(['percinli', 'sivama']),
    boxShape: z.string().optional(),
    
    // Keeping dimensions but making them optional for now as user said "we will add measurements one by one"
    dimensions: z.object({
        length: z.coerce.number().optional(),
        width: z.coerce.number().optional(),
        depth: z.coerce.number().optional(),
    }).optional(),

    inks: z.object({
        cmyk: z.boolean().default(false),
        white: z.boolean().default(false),
        pantones: z.array(z.string()).max(10, 'En fazla 10 Pantone girebilirsiniz').default([]),
        goldLak: z.object({ has: z.boolean().default(false), code: z.string().optional() }),
        emaye: z.object({ has: z.boolean().default(false), code: z.string().optional() }),
        astar: z.object({ has: z.boolean().default(false), code: z.string().optional() }),
        silverLak: z.object({ has: z.boolean().default(false), code: z.string().optional() }),
        mold: z.boolean().default(false), // Kalıp
    }),

    features: z.object({
        hasLid: z.boolean(),
        hasWindow: z.boolean(),
        extras: z.string().optional().default(''),
        gofre: z.boolean().default(false),
        gofreDetails: z.object({
            count: z.coerce.number().optional(),
            notes: z.string().optional(),
        }).optional(),
        // foodGrade removed
    }),
    details: z.string().optional(),
    windowDetails: z.object({
        width: z.coerce.number().optional(),
        height: z.coerce.number().optional(),
        count: z.coerce.number().optional(),
    }).optional(),
    lidDetails: z.object({
        material: z.string().optional(),
        paint: z.string().optional(),
        notes: z.string().optional(),
        hasGofre: z.boolean().default(false),
        gofreDetails: z.object({
            count: z.coerce.number().optional(),
            notes: z.string().optional(),
        }).optional(),
        hasWindow: z.boolean().default(false),
        windowDimensions: z.object({
            width: z.coerce.number().optional(),
            height: z.coerce.number().optional(),
        }).optional(),
        dimensions: z.object({
            length: z.coerce.number().optional(),
            width: z.coerce.number().optional(),
            depth: z.coerce.number().optional(),
        }).optional(),
    }).optional(),
    images: z.object({
        customer: z.array(z.string()).optional(),
        // design removed
    }).optional(),
});

interface ProductFormProps {
    initialData?: Product;
    onSubmit: (data: ProductFormData) => void;
    onCancel: () => void;
}

export function ProductForm({ initialData, onSubmit, onCancel }: ProductFormProps) {
    const { molds } = useMolds();
    const { register, handleSubmit, watch, setValue, getValues, formState: { errors } } = useForm<ProductFormData>({
        resolver: zodResolver(productSchema) as any,
        defaultValues: initialData ? {
            ...initialData,
            // Map old description to name if editing old data
            name: initialData.name || initialData.description || '',
            productType: initialData.productType || 'percinli',
            // Default inks if not present
            inks: initialData.inks || {
                cmyk: false, white: false, pantones: [], 
                goldLak: { has: false }, emaye: { has: false }, astar: { has: false }, silverLak: { has: false },
                mold: false
            }
        } : {
            code: 'Otomatik',
            name: '',
            productType: 'percinli',
            dimensions: { length: 0, width: 0, depth: 0 },
            inks: {
                cmyk: false, white: false, pantones: [], 
                goldLak: { has: false }, emaye: { has: false }, astar: { has: false }, silverLak: { has: false },
                mold: false
            },
            features: { hasLid: false, hasWindow: false, extras: '', gofre: false },
            details: '',
            windowDetails: { width: 0, height: 0, count: 1 },
            lidDetails: { 
                material: '', paint: '', notes: '', hasGofre: false, hasWindow: false, 
                windowDimensions: { width: 0, height: 0 },
                dimensions: { length: 0, width: 0, depth: 0 }
            },
            images: { customer: [] },
        },
    });

    const productType = watch('productType');
    const boxShape = watch('boxShape');
    const hasLid = watch('features.hasLid');
    const hasWindow = watch('features.hasWindow');
    const lidHasWindow = watch('lidDetails.hasWindow');
    const customerImages = watch('images.customer') || [];
    const pantones = watch('inks.pantones') || [];
    const [newPantone, setNewPantone] = useState('');

    // Dimension helpers for Percinli Square
    const dimLength = watch('dimensions.length');
    const dimWidth = watch('dimensions.width');
    const dimDepth = watch('dimensions.depth');
    const currentBaseDim = (dimLength && dimWidth) ? `${dimLength}x${dimWidth}` : '';

    const handleBaseDimChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
        const val = e.target.value;
        if (!val) {
            setValue('dimensions.length', undefined);
            setValue('dimensions.width', undefined);
            return;
        }
        const [l, w] = val.split('x').map(Number);
        setValue('dimensions.length', l);
        setValue('dimensions.width', w);
    };

    const handleHeartDimChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
        const val = e.target.value;
        if (!val) {
            setValue('dimensions.length', undefined);
            setValue('dimensions.width', undefined);
            setValue('dimensions.depth', undefined);
            return;
        }
        const parts = val.split('x').map(Number);
        if (parts.length === 3) {
            setValue('dimensions.length', parts[0]);
            setValue('dimensions.width', parts[1]);
            setValue('dimensions.depth', parts[2]);
        } else {
            setValue('dimensions.length', parts[0]);
            setValue('dimensions.width', parts[1]);
            // Clear depth to allow manual input and differentiate from fixed depth options
            setValue('dimensions.depth', undefined);
        }
    };

    const handleConicDimChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
        const val = e.target.value;
        if (!val) {
            setValue('dimensions.length', undefined);
            setValue('dimensions.width', undefined);
            setValue('dimensions.depth', undefined);
            return;
        }
        const parts = val.split('x').map(Number);
        if (parts.length === 3) {
            setValue('dimensions.length', parts[0]);
            setValue('dimensions.width', parts[1]);
            setValue('dimensions.depth', parts[2]);
        }
    };

    // Watch Inks for conditional inputs
    const hasGoldLak = watch('inks.goldLak.has');
    const hasEmaye = watch('inks.emaye.has');
    const hasAstar = watch('inks.astar.has');
    const hasSilverLak = watch('inks.silverLak.has');

    // Reset boxShape if not valid for the selected productType
    useEffect(() => {
        const currentShape = getValues('boxShape');
        if (!currentShape) return;

        if (productType === 'percinli') {
            if (!PERCINLI_SHAPES.includes(currentShape as any)) {
                setValue('boxShape', undefined);
            }
        } else if (productType === 'sivama') {
            // Check against dynamic molds if loaded
            if (molds.length > 0) {
                const validShapes = molds
                    .filter(m => m.productType === 'sivama')
                    .map(m => m.dimensions);
                if (!validShapes.includes(currentShape)) {
                    setValue('boxShape', undefined);
                }
            }
        }
    }, [productType, setValue, getValues, molds]);

    const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
        const files = e.target.files;
        if (!files) return;

        if (customerImages.length + files.length > 2) {
            alert('En fazla 2 resim yükleyebilirsiniz.');
            return;
        }

        const uploadedUrls: string[] = [];

        for (let i = 0; i < files.length; i++) {
            const file = files[i];
            const formData = new FormData();
            formData.append('image', file);

            try {
                const response = await fetch('/api/upload', {
                    method: 'POST',
                    body: formData,
                });
                
                if (response.ok) {
                    const data = await response.json();
                    uploadedUrls.push(data.url);
                } else {
                    console.error('Upload failed');
                    alert('Resim yüklenirken bir hata oluştu.');
                }
            } catch (error) {
                console.error('Error uploading image:', error);
                alert('Resim yüklenirken bir hata oluştu.');
            }
        }
        
        if (uploadedUrls.length > 0) {
             const newImages = [...customerImages, ...uploadedUrls];
             setValue(`images.customer`, newImages);
        }
    };

    const removeImage = (index: number) => {
        const newImages = customerImages.filter((_, i) => i !== index);
        setValue(`images.customer`, newImages);
    };

    const addPantone = () => {
        if (newPantone.trim()) {
            if (pantones.length >= 10) {
                alert('En fazla 10 Pantone kodu girebilirsiniz.');
                return;
            }
            setValue('inks.pantones', [...pantones, newPantone.trim()]);
            setNewPantone('');
        }
    };

    const removePantone = (index: number) => {
        setValue('inks.pantones', pantones.filter((_, i) => i !== index));
    };

    return (
        <form onSubmit={handleSubmit(onSubmit as any)} className="space-y-6">
            {/* TEMEL BILGILER */}
            <div className="space-y-4">
                <h4 className="text-sm font-semibold text-slate-800 border-b pb-2">Temel Bilgiler</h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-1">
                        <label className="text-sm font-medium text-slate-700">Ürün Kodu</label>
                        <input
                            disabled
                            value={initialData?.code || "Otomatik Oluşturulacak (GMP...)"}
                            className="w-full px-3 py-2 border border-slate-200 bg-slate-50 rounded-lg text-slate-500 cursor-not-allowed"
                            aria-label="Ürün Kodu"
                        />
                    </div>
                    <div className="space-y-1">
                        <label className="text-sm font-medium text-slate-700">Ürün Adı</label>
                        <input
                            {...register('name')}
                            className={cn(
                                "w-full px-3 py-2 border rounded-lg outline-none focus:ring-2 focus:ring-indigo-500 transition-all",
                                errors.name ? "border-red-500" : "border-slate-300"
                            )}
                            placeholder="Örn: Yuvarlak Kutu"
                            aria-label="Ürün Adı"
                        />
                        {errors.name && <p className="text-xs text-red-500">{errors.name.message}</p>}
                    </div>
                </div>
            </div>

            {/* ÜRÜN ŞEKLİ */}
            <div className="space-y-4">
                <h4 className="text-sm font-semibold text-slate-800 border-b pb-2">Ürün Şekli</h4>
                <div className="space-y-4">
                    <div className="space-y-2">
                        <label className="text-sm font-medium text-slate-700">Ürün Tipi</label>
                        <div className="flex gap-4">
                            {PRODUCT_TYPES.map(type => (
                                <label key={type.value} className="flex items-center gap-2 cursor-pointer">
                                    <input
                                        type="radio"
                                        value={type.value}
                                        {...register('productType')}
                                        className="w-4 h-4 text-indigo-600 border-gray-300 focus:ring-indigo-500"
                                        aria-label={type.label}
                                    />
                                    <span className="text-sm text-slate-700">{type.label}</span>
                                </label>
                            ))}
                        </div>
                    </div>

                    {(productType === 'percinli' || productType === 'sivama') && (
                        <div className="space-y-2 animate-in fade-in slide-in-from-top-2">
                            <label className="text-sm font-medium text-slate-700">Kutu Şekli / Ölçü</label>
                            <select
                                {...register('boxShape')}
                                className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                aria-label="Kutu Şekli"
                            >
                                <option value="">Seçiniz...</option>
                                {productType === 'percinli' && PERCINLI_SHAPES.map(shape => (
                                    <option key={shape} value={shape}>{shape}</option>
                                ))}
                                {productType === 'sivama' && molds
                                    .filter(m => m.productType === 'sivama')
                                    .map(m => (
                                    <option key={m.id} value={m.dimensions}>{m.dimensions}</option>
                                ))}
                            </select>
                        </div>
                    )}

                    {/* Perçinli + Kare -> Base Dimensions + Depth */}
                    {productType === 'percinli' && boxShape === 'Kare' && (
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Taban Ölçüsü (mm)</label>
                                <select
                                    value={currentBaseDim}
                                    onChange={handleBaseDimChange}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                    aria-label="Taban Ölçüsü"
                                >
                                    <option value="">Seçiniz...</option>
                                    {molds.filter(m => m.boxShape === 'Kare').sort(sortDimensions).map(m => (
                                        <option key={m.id} value={m.dimensions}>{m.dimensions}</option>
                                    ))}
                                </select>
                            </div>
                            {currentBaseDim && (
                                <div className="space-y-2 animate-in fade-in slide-in-from-left-2">
                                    <label className="text-sm font-medium text-slate-700">Boy / Yükseklik (mm)</label>
                                    <input
                                        type="number"
                                        placeholder="0"
                                        {...register('dimensions.depth')}
                                        className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                        aria-label="Yükseklik"
                                    />
                                </div>
                            )}
                        </div>
                    )}

                    {/* Perçinli + Oval -> Base Dimensions + Depth */}
                    {productType === 'percinli' && boxShape === 'Oval' && (
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Taban Ölçüsü (mm)</label>
                                <select
                                    value={currentBaseDim}
                                    onChange={handleBaseDimChange}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                    aria-label="Taban Ölçüsü"
                                >
                                    <option value="">Seçiniz...</option>
                                    {molds.filter(m => m.boxShape === 'Oval').sort(sortDimensions).map(m => (
                                        <option key={m.id} value={m.dimensions}>{m.dimensions}</option>
                                    ))}
                                </select>
                            </div>
                            {currentBaseDim && (
                                <div className="space-y-2 animate-in fade-in slide-in-from-left-2">
                                    <label className="text-sm font-medium text-slate-700">Boy / Yükseklik (mm)</label>
                                    <input
                                        type="number"
                                        placeholder="0"
                                        {...register('dimensions.depth')}
                                        className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                        aria-label="Yükseklik"
                                    />
                                </div>
                            )}
                        </div>
                    )}
                    
                    {/* Perçinli + Sekizgen -> Base Dimensions + Depth */}
                    {productType === 'percinli' && boxShape === 'Sekizgen' && (
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Taban Ölçüsü (mm)</label>
                                <select
                                    value={currentBaseDim}
                                    onChange={handleBaseDimChange}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                    aria-label="Taban Ölçüsü"
                                >
                                    <option value="">Seçiniz...</option>
                                    {molds.filter(m => m.boxShape === 'Sekizgen').sort(sortDimensions).map(m => (
                                        <option key={m.id} value={m.dimensions}>{m.dimensions}</option>
                                    ))}
                                </select>
                            </div>
                            {currentBaseDim && (
                                <div className="space-y-2 animate-in fade-in slide-in-from-left-2">
                                    <label className="text-sm font-medium text-slate-700">Boy / Yükseklik (mm)</label>
                                    <input
                                        type="number"
                                        placeholder="0"
                                        {...register('dimensions.depth')}
                                        className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                    />
                                </div>
                            )}
                        </div>
                    )}

                    {/* Perçinli + Dikdörtgen -> Base Dimensions + Depth */}
                    {productType === 'percinli' && boxShape === 'Dikdörtgen' && (
                        <div className="grid grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Taban Ölçüsü (mm)</label>
                                <select
                                    value={currentBaseDim}
                                    onChange={handleBaseDimChange}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                >
                                    <option value="">Seçiniz...</option>
                                    {molds.filter(m => m.boxShape === 'Dikdörtgen').sort(sortDimensions).map(m => (
                                        <option key={m.id} value={m.dimensions}>{m.dimensions}</option>
                                    ))}
                                </select>
                            </div>
                            {currentBaseDim && (
                                <div className="space-y-2 animate-in fade-in slide-in-from-left-2">
                                    <label className="text-sm font-medium text-slate-700">Boy / Yükseklik (mm)</label>
                                    <input
                                        type="number"
                                        placeholder="0"
                                        {...register('dimensions.depth')}
                                        className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                    />
                                </div>
                            )}
                        </div>
                    )}

                    {/* Perçinli + Yuvarlak -> Diameter + Depth */}
                    {productType === 'percinli' && boxShape === 'Yuvarlak' && (
                        <div className="grid grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Çap (Ø)</label>
                                <select
                                    value={currentBaseDim}
                                    onChange={handleBaseDimChange}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                >
                                    <option value="">Seçiniz...</option>
                                    {molds.filter(m => m.boxShape === 'Yuvarlak').sort(sortDimensions).map(m => (
                                        <option key={m.id} value={`${m.dimensions}x${m.dimensions}`}>{m.label || `Ø${m.dimensions}`}</option>
                                    ))}
                                </select>
                            </div>
                            {currentBaseDim && (
                                <div className="space-y-2 animate-in fade-in slide-in-from-left-2">
                                    <label className="text-sm font-medium text-slate-700">Boy / Yükseklik (mm)</label>
                                    <input
                                        type="number"
                                        placeholder="0"
                                        {...register('dimensions.depth')}
                                        className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                    />
                                </div>
                            )}
                        </div>
                    )}

                    {/* Perçinli + Kalpli -> Specific Logic */}
                    {productType === 'percinli' && boxShape === 'Kalpli' && (
                        <div className="grid grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Taban Ölçüsü (mm)</label>
                                <select
                                    value={(dimLength && dimWidth) ? (
                                        molds.filter(m => m.boxShape === 'Kalpli').find(m => 
                                            m.dimensions === `${dimLength}x${dimWidth}x${dimDepth}`
                                        )?.dimensions || `${dimLength}x${dimWidth}`
                                    ) : ''}
                                    onChange={handleHeartDimChange}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                >
                                    <option value="">Seçiniz...</option>
                                    {molds.filter(m => m.boxShape === 'Kalpli').sort(sortDimensions).map(m => (
                                        <option key={m.id} value={m.dimensions}>{m.label || m.dimensions}</option>
                                    ))}
                                </select>
                            </div>
                            
                            {/* Show depth input unless we have matched a 3-part mold dimensions exactly */}
                            {dimLength && dimWidth && !molds.some(m => m.boxShape === 'Kalpli' && m.dimensions === `${dimLength}x${dimWidth}x${dimDepth}`) && (
                                <div className="space-y-2 animate-in fade-in slide-in-from-left-2">
                                    <label className="text-sm font-medium text-slate-700">Boy / Yükseklik (mm)</label>
                                    <input
                                        type="number"
                                        placeholder="0"
                                        {...register('dimensions.depth')}
                                        className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                    />
                                </div>
                            )}
                        </div>
                    )}

                    {/* Perçinli + Tepsi -> Base Dimensions + Special Label Depth */}
                    {productType === 'percinli' && boxShape === 'Tepsi' && (
                        <div className="grid grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Taban Ölçüsü (mm)</label>
                                <select
                                    value={currentBaseDim}
                                    onChange={handleBaseDimChange}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                >
                                    <option value="">Seçiniz...</option>
                                    {molds.filter(m => m.boxShape === 'Tepsi').sort(sortDimensions).map(m => (
                                        <option key={m.id} value={m.dimensions}>{m.label || m.dimensions}</option>
                                    ))}
                                </select>
                            </div>
                            {currentBaseDim && (
                                <div className="space-y-2 animate-in fade-in slide-in-from-left-2">
                                    <label className="text-sm font-medium text-slate-700">Ek ölçü varsa belirtin</label>
                                    <input
                                        type="number"
                                        placeholder="0"
                                        {...register('dimensions.depth')}
                                        className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                    />
                                </div>
                            )}
                        </div>
                    )}

                    {/* Perçinli + Konik -> Fixed Dimensions (No extra depth input) */}
                    {productType === 'percinli' && boxShape === 'Konik' && (
                        <div className="grid grid-cols-2 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Ölçü (mm)</label>
                                <select
                                    value={(dimLength && dimWidth && dimDepth) ? `${dimLength}x${dimWidth}x${dimDepth}` : ''}
                                    onChange={handleConicDimChange}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                >
                                    <option value="">Seçiniz...</option>
                                    {molds.filter(m => m.boxShape === 'Konik').sort(sortDimensions).map(m => (
                                        <option key={m.id} value={m.dimensions}>{m.label || m.dimensions}</option>
                                    ))}
                                </select>
                            </div>
                        </div>
                    )}

                    {/* Perçinli + Özel -> Manual Dimensions */}
                    {productType === 'percinli' && boxShape === 'Özel' && (
                        <div className="grid grid-cols-3 gap-4 animate-in fade-in slide-in-from-top-2">
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">En (mm)</label>
                                <input
                                    type="number"
                                    placeholder="0"
                                    {...register('dimensions.width')}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                />
                            </div>
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Genişlik (mm)</label>
                                <input
                                    type="number"
                                    placeholder="0"
                                    {...register('dimensions.length')}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                />
                            </div>
                            <div className="space-y-2">
                                <label className="text-sm font-medium text-slate-700">Boy (mm)</label>
                                <input
                                    type="number"
                                    placeholder="0"
                                    {...register('dimensions.depth')}
                                    className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500"
                                />
                            </div>
                        </div>
                    )}

                    {/* Placeholder for Dimensions - Show only if NOT (Percinli + Kare/Oval/Sekizgen/Dikdörtgen/Yuvarlak/Kalpli/Tepsi/Konik/Özel) because we handle it above */}
                    {!(productType === 'percinli' && (boxShape === 'Kare' || boxShape === 'Oval' || boxShape === 'Sekizgen' || boxShape === 'Dikdörtgen' || boxShape === 'Yuvarlak' || boxShape === 'Kalpli' || boxShape === 'Tepsi' || boxShape === 'Konik' || boxShape === 'Özel')) && (
                        <div className="p-3 bg-yellow-50 border border-yellow-200 rounded text-sm text-yellow-800">
                            Ölçüler kategorilere göre daha sonra detaylandırılacaktır.
                        </div>
                    )}
                </div>
            </div>

            {/* MÜREKKEPLER */}
            <div className="space-y-4">
                <h4 className="text-sm font-semibold text-slate-800 border-b pb-2">Mürekkepler</h4>
                
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    <label className="flex items-center gap-2 p-3 border rounded-lg cursor-pointer hover:bg-slate-50">
                        <input type="checkbox" {...register('inks.cmyk')} className="w-4 h-4 text-indigo-600 rounded" />
                        <span className="text-sm font-medium">CMYK</span>
                    </label>
                    <label className="flex items-center gap-2 p-3 border rounded-lg cursor-pointer hover:bg-slate-50">
                        <input type="checkbox" {...register('inks.white')} className="w-4 h-4 text-indigo-600 rounded" />
                        <span className="text-sm font-medium">Beyaz</span>
                    </label>
                    <label className="flex items-center gap-2 p-3 border rounded-lg cursor-pointer hover:bg-slate-50">
                        <input type="checkbox" {...register('inks.mold')} className="w-4 h-4 text-indigo-600 rounded" />
                        <span className="text-sm font-medium">Kalıp</span>
                    </label>
                </div>

                <div className="space-y-2">
                    <label className="text-sm font-medium text-slate-700">Pantone Kodları</label>
                    <div className="flex gap-2">
                        <input 
                            value={newPantone}
                            onChange={(e) => setNewPantone(e.target.value)}
                            placeholder="Kod (Örn: C0000)"
                            className="flex-1 px-3 py-1.5 border rounded text-sm outline-none focus:border-indigo-500"
                            aria-label="Pantone Kodu"
                            onKeyDown={(e) => {
                                if (e.key === 'Enter') {
                                    e.preventDefault();
                                    addPantone();
                                }
                            }}
                        />
                        <button
                            type="button"
                            onClick={addPantone}
                            className="text-xs flex items-center gap-1 bg-indigo-50 text-indigo-600 px-3 py-1.5 rounded hover:bg-indigo-100 whitespace-nowrap"
                        >
                            <Plus size={14} /> Ekle
                        </button>
                    </div>
                    
                    {pantones.length > 0 ? (
                        <div className="flex flex-wrap gap-2 mt-2">
                            {pantones.map((code, index) => (
                                <div key={index} className="flex items-center gap-1 bg-slate-100 px-2 py-1 rounded text-sm border border-slate-200">
                                    <span>{code}</span>
                                    <button type="button" onClick={() => removePantone(index)} className="text-slate-400 hover:text-red-500" aria-label="Pantone Sil">
                                        <X size={14} />
                                    </button>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <p className="text-xs text-slate-400 italic mt-1">Henüz pantone kodu eklenmedi.</p>
                    )}
                </div>

                <div className="space-y-3 pt-2">
                    {/* Gold Lak */}
                    <div className="flex items-center gap-4">
                        <label className="flex items-center gap-2 w-32">
                            <input type="checkbox" {...register('inks.goldLak.has')} className="w-4 h-4 text-indigo-600 rounded" />
                            <span className="text-sm">Gold Lak</span>
                        </label>
                        {hasGoldLak && (
                            <input 
                                {...register('inks.goldLak.code')} 
                                placeholder="Kod giriniz" 
                                className="flex-1 px-3 py-1.5 border rounded text-sm outline-none focus:border-indigo-500"
                            />
                        )}
                    </div>
                    {/* Emaye */}
                    <div className="flex items-center gap-4">
                        <label className="flex items-center gap-2 w-32">
                            <input type="checkbox" {...register('inks.emaye.has')} className="w-4 h-4 text-indigo-600 rounded" />
                            <span className="text-sm">Emaye</span>
                        </label>
                        {hasEmaye && (
                            <input 
                                {...register('inks.emaye.code')} 
                                placeholder="Kod giriniz" 
                                className="flex-1 px-3 py-1.5 border rounded text-sm outline-none focus:border-indigo-500"
                            />
                        )}
                    </div>
                    {/* Astar */}
                    <div className="flex items-center gap-4">
                        <label className="flex items-center gap-2 w-32">
                            <input type="checkbox" {...register('inks.astar.has')} className="w-4 h-4 text-indigo-600 rounded" />
                            <span className="text-sm">Astar</span>
                        </label>
                        {hasAstar && (
                            <input 
                                {...register('inks.astar.code')} 
                                placeholder="Kod giriniz" 
                                className="flex-1 px-3 py-1.5 border rounded text-sm outline-none focus:border-indigo-500"
                            />
                        )}
                    </div>
                    {/* Silver Lak */}
                    <div className="flex items-center gap-4">
                        <label className="flex items-center gap-2 w-32">
                            <input type="checkbox" {...register('inks.silverLak.has')} className="w-4 h-4 text-indigo-600 rounded" />
                            <span className="text-sm">Silver Lak</span>
                        </label>
                        {hasSilverLak && (
                            <input 
                                {...register('inks.silverLak.code')} 
                                placeholder="Kod giriniz" 
                                className="flex-1 px-3 py-1.5 border rounded text-sm outline-none focus:border-indigo-500"
                            />
                        )}
                    </div>
                </div>
            </div>

            {/* ÖZELLİKLER & DETAYLAR */}
            <div className="space-y-4">
                <h4 className="text-sm font-semibold text-slate-800 border-b pb-2">Özellikler & Detaylar</h4>

                <div className="flex flex-wrap gap-6 mb-4">
                    <label className="flex items-center gap-2 text-sm text-slate-700 cursor-pointer select-none">
                        <input
                            type="checkbox"
                            {...register('features.hasWindow')}
                            className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500 border-gray-300"
                        />
                        Pencere Var
                    </label>
                    <label className="flex items-center gap-2 text-sm text-slate-700 cursor-pointer select-none">
                        <input
                            type="checkbox"
                            {...register('features.hasLid')}
                            className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500 border-gray-300"
                        />
                        Kapak Var
                    </label>
                    <label className="flex items-center gap-2 text-sm text-slate-700 cursor-pointer select-none">
                        <input
                            type="checkbox"
                            {...register('features.gofre')}
                            className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500 border-gray-300"
                        />
                        Gofre
                    </label>
                </div>

                {hasWindow && (
                    <div className="p-4 bg-slate-50 rounded-lg border border-slate-200 animate-in fade-in slide-in-from-top-2 duration-200">
                        <h5 className="text-sm font-medium text-indigo-900 mb-3 flex items-center gap-2">
                            <span className="w-1.5 h-1.5 rounded-full bg-indigo-500"></span>
                            Pencere Ölçüleri
                        </h5>
                        <div className="grid grid-cols-3 gap-4">
                            <div className="space-y-1">
                                <label className="text-xs font-medium text-slate-600">Genişlik (mm)</label>
                                <input
                                    type="number"
                                    {...register('windowDetails.width')}
                                    className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-sm outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"
                                />
                            </div>
                            <div className="space-y-1">
                                <label className="text-xs font-medium text-slate-600">Yükseklik (mm)</label>
                                <input
                                    type="number"
                                    {...register('windowDetails.height')}
                                    className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-sm outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"
                                />
                            </div>
                            <div className="space-y-1">
                                <label className="text-xs font-medium text-slate-600">Pencere Adet</label>
                                <input
                                    type="number"
                                    {...register('windowDetails.count')}
                                    className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-sm outline-none focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500"
                                />
                            </div>
                        </div>
                    </div>
                )}

                {hasLid && (
                    <div className="p-4 bg-slate-50 rounded-lg border border-slate-200 animate-in fade-in slide-in-from-top-2 duration-200 space-y-4">
                        <h5 className="text-sm font-medium text-indigo-900 flex items-center gap-2">
                            <span className="w-1.5 h-1.5 rounded-full bg-indigo-500"></span>
                            Kapak Bilgileri
                        </h5>
                        
                        <div className="flex gap-6">
                             <label className="flex items-center gap-2 text-xs text-slate-700 cursor-pointer select-none">
                                <input
                                    type="checkbox"
                                    {...register('lidDetails.hasGofre')}
                                    className="w-3.5 h-3.5 rounded text-indigo-600 focus:ring-indigo-500 border-gray-300"
                                />
                                Kapakta Gofre
                            </label>
                             <label className="flex items-center gap-2 text-xs text-slate-700 cursor-pointer select-none">
                                <input
                                    type="checkbox"
                                    {...register('lidDetails.hasWindow')}
                                    className="w-3.5 h-3.5 rounded text-indigo-600 focus:ring-indigo-500 border-gray-300"
                                />
                                Kapakta Pencere
                            </label>
                        </div>

                        {/* Lid Gofre Details */}
                        {watch('lidDetails.hasGofre') && (
                            <div className="grid grid-cols-2 gap-4 p-3 bg-white rounded border border-slate-200">
                                <div className="space-y-1">
                                    <label className="text-xs font-medium text-slate-600">Gofre Adet</label>
                                    <input
                                        type="number"
                                        {...register('lidDetails.gofreDetails.count')}
                                        className="w-full px-2 py-1.5 bg-slate-50 border border-slate-200 rounded text-sm outline-none focus:border-indigo-500"
                                    />
                                </div>
                                <div className="space-y-1">
                                    <label className="text-xs font-medium text-slate-600">Konum / Notlar</label>
                                    <input
                                        {...register('lidDetails.gofreDetails.notes')}
                                        placeholder="Örn: Tam orta..."
                                        className="w-full px-2 py-1.5 bg-slate-50 border border-slate-200 rounded text-sm outline-none focus:border-indigo-500"
                                    />
                                </div>
                            </div>
                        )}

                        {lidHasWindow && (
                            <div className="grid grid-cols-2 gap-4 p-3 bg-white rounded border border-slate-200">
                                <div className="space-y-1">
                                    <label className="text-xs font-medium text-slate-600">Pencere Genişlik</label>
                                    <input
                                        type="number"
                                        {...register('lidDetails.windowDimensions.width')}
                                        className="w-full px-2 py-1.5 bg-slate-50 border border-slate-200 rounded text-sm outline-none focus:border-indigo-500"
                                    />
                                </div>
                                <div className="space-y-1">
                                    <label className="text-xs font-medium text-slate-600">Pencere Yükseklik</label>
                                    <input
                                        type="number"
                                        {...register('lidDetails.windowDimensions.height')}
                                        className="w-full px-2 py-1.5 bg-slate-50 border border-slate-200 rounded text-sm outline-none focus:border-indigo-500"
                                    />
                                </div>
                            </div>
                        )}
                        
                        <div className="space-y-1">
                            <label className="text-xs font-medium text-slate-600">Malzeme</label>
                            <input
                                {...register('lidDetails.material')}
                                placeholder="Örn: PVC, Asetat..."
                                className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-sm outline-none focus:border-indigo-500"
                            />
                        </div>
                    </div>
                )}
            </div>
            
            {/* ÜRÜN DETAYLARI - Keep as is */}
            <div className="space-y-4">
                <h4 className="text-sm font-semibold text-slate-800 border-b pb-2">Ürün Detayları</h4>
                <div className="space-y-1">
                    <textarea
                        {...register('details')}
                        className="w-full px-3 py-2 border border-slate-300 rounded-lg outline-none focus:ring-2 focus:ring-indigo-500 min-h-[100px]"
                        placeholder="Ek özellikler ve detaylar..."
                    />
                </div>
            </div>

            {/* ÜRÜN GÖRSELLERİ */}
            <div className="space-y-4">
                <h4 className="text-sm font-semibold text-slate-800 border-b pb-2">Ürün Görselleri</h4>
                
                <div className="space-y-3">
                    <label className="block text-sm font-medium text-slate-700">Müşteri Görseli (Jpeg, Png, Pdf)</label>
                    <div className="flex gap-4">
                        {customerImages.map((url, index) => (
                            <div key={index} className="relative w-24 h-24 border rounded-lg overflow-hidden group">
                                <img src={url} alt={`Customer ${index + 1}`} className="w-full h-full object-cover" />
                                <button
                                    type="button"
                                    onClick={() => removeImage(index)}
                                    className="absolute top-1 right-1 bg-red-500 text-white p-1 rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
                                    aria-label="Resmi Sil"
                                >
                                    <X size={12} />
                                </button>
                            </div>
                        ))}
                        {customerImages.length < 2 && (
                            <label className="w-24 h-24 border-2 border-dashed border-slate-300 rounded-lg flex flex-col items-center justify-center cursor-pointer hover:border-indigo-500 hover:bg-indigo-50 transition-all">
                                <Upload className="w-6 h-6 text-slate-400 mb-1" />
                                <span className="text-[10px] text-slate-500">Yükle</span>
                                <input type="file" className="hidden" accept="image/jpeg,image/png,application/pdf" onChange={handleImageUpload} aria-label="Resim Yükle" />
                            </label>
                        )}
                    </div>
                </div>
            </div>

            <div className="flex justify-end gap-3 pt-4 border-t">
                <button
                    type="button"
                    onClick={onCancel}
                    className="px-4 py-2 text-sm font-medium text-slate-700 bg-white border border-slate-300 rounded-lg hover:bg-slate-50"
                    aria-label="İptal"
                >
                    İptal
                </button>
                <button
                    type="submit"
                    className="px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-lg hover:bg-indigo-700"
                    aria-label="Kaydet"
                >
                    Kaydet
                </button>
            </div>
        </form>
    );
}