export const ORDER_STATUS_MAP: Record<string, { label: string, color: string }> = {
    created: { label: 'Oluşturuldu', color: 'bg-slate-100 text-slate-700' },
    offer_sent: { label: 'Teklif Oluşturuldu', color: 'bg-blue-50 text-blue-700' },
    waiting_manager_approval: { label: 'GM Onayı Bekleniyor', color: 'bg-orange-100 text-orange-800' },
    manager_approved: { label: 'GM Onayladı', color: 'bg-blue-100 text-blue-800' },
    revision_requested: { label: 'Revize İsteniyor', color: 'bg-red-50 text-red-700' },
    offer_accepted: { label: 'Teklif Kabul Edildi', color: 'bg-blue-200 text-blue-900' },
    offer_cancelled: { label: 'Teklif İptal Edildi', color: 'bg-red-50 text-red-700' },
    supply_design_process: { label: 'Tedarik ve Tasarım Aşamasında', color: 'bg-purple-100 text-purple-800' },
    design_waiting: { label: 'Tasarım Bekleniyor', color: 'bg-purple-50 text-purple-700' },
    design_approved: { label: 'Tasarım Onaylandı', color: 'bg-purple-100 text-purple-800' },
    supply_waiting: { label: 'Tedarik Madde Bekleniyor', color: 'bg-cyan-50 text-cyan-700' },
    supply_completed: { label: 'Tedarik Tamamlandı', color: 'bg-cyan-100 text-cyan-800' },
    production_planned: { label: 'Üretim Planlamasında', color: 'bg-amber-50 text-amber-700' },
    production_started: { label: 'Üretim Başladı', color: 'bg-amber-100 text-amber-800' },
    production_completed: { label: 'Üretim Tamamlandı', color: 'bg-amber-200 text-amber-900' },
    invoice_waiting: { label: 'Fatura - İrsaliye Bekleniyor', color: 'bg-lime-50 text-lime-700' },
    invoice_added: { label: 'Fatura - İrsaliye Eklendi', color: 'bg-lime-100 text-lime-800' },
    shipping_waiting: { label: 'Sevkiyat Bekleniyor', color: 'bg-indigo-50 text-indigo-700' },
    shipping_completed: { label: 'Sevkiyat Bitti', color: 'bg-indigo-100 text-indigo-800' },
    order_completed: { label: 'Sipariş Tamamlandı', color: 'bg-green-200 text-green-900' },
    order_cancelled: { label: 'Sipariş İptal Edildi', color: 'bg-red-100 text-red-800' },
    // Legacy/Fallback statuses
    shipped: { label: 'Teslim Edildi', color: 'bg-emerald-100 text-emerald-800' },
};
